python pcnn_train.py \
--batch_size 32 \
--sample_batch_size 12 \
--sampling_interval 50 \
--save_interval 50 \
--dataset cpen455 \
--nr_resnet 3 \
--nr_filters 100 \
--nr_logistic_mix 10 \
--lr_decay 0.9999 \
--max_epochs 300 \
--embedding_dim 64 \
--model conditional \
--en_wandb True